config/routes.rb
BotsInc::Application.routes.draw do
  devise_for :users

  resources :items

  resources :basket_items, only: [:create]

  root to: 'homepage#show'

end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  has_many :basket_items
  has_many :items, through: :basket_items
end

app/models/basket_item.rb
class BasketItem < ActiveRecord::Base
  
  belongs_to :basket
  belongs_to :item
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :robot
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :basket

  belongs_to :user
end

app/models/robot.rb
class Robot < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :basket
  has_many :purchases


  def basket
    @basket ||= Basket.find_or_create_by(user_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    BasketItem.create(item_id: item.id, basket_id: params[:basket_id])
    redirect_to items_path, notice: "#{item.name} added to basket."
  end


end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/homepage/show.html.erb
<div id="hero">
  <h1>Bots, Inc.</h1>
  <h2>Trust robots with all your purchasing needs.</h2>
</div>

<div>
  <p>Buy whatever you want</p>
  <p> View My Basket </p>
  <p>Robots package it up and deliver it to your door.</p>
  <p>Simple.</p>
</div>

<%= link_to "Browse our items", items_path %>

app/views/items/_item.html.erb
<div id='item-<%= item.id %>'>
  <h3><%= item.name %></h3>

  <p><%= item.description %></p>
  <p>"View my basket"</p>

  <div class="price">
    <%= number_to_currency (item.price/100), unit: "฿" %>
  </div>

  <div>
    <%= button_to "Add to basket", basket_items_path(item_id: item.id, basket_id: current_user.basket.id) %>
  </div>
</div>

app/views/items/index.html.erb
<%= render @items %>
  <p>"View my basket"</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BotsInc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <div class="flash notice">
      <%= flash[:notice] %>
    </div>
  <% end %>
  
  <div class="nav">
    <%= link_to "Log in", new_user_session_path unless user_signed_in? %>
  </div>

<%= yield %>

</body>
</html>